# Generated by Django 5.1.5 on 2025-01-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='account_number',
            new_name='card_number',
        ),
    ]
