# Generated by Django 5.1.5 on 2025-01-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_rename_account_number_client_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='bridge.client'),
        ),
    ]
