# Generated by Django 5.1.5 on 2025-01-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_alter_bankaccount_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pin',
            field=models.CharField(),
        ),
    ]
