# Generated by Django 5.1.5 on 2025-01-25 23:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0005_transaction_balance_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('REJECTED', 'Rejecté'), ('COMPLETE', 'Traité')], default='COMPLETE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')]),
        ),
    ]
