# Generated by Django 5.1.5 on 2025-01-26 00:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0006_transaction_status_alter_bankaccount_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('REJECTED', 'Rejecté'), ('COMPLETE', 'Traité')], editable=False),
        ),
    ]
