# Generated by Django 5.1.5 on 2025-01-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0007_transaction_reference_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
